# Travis CI config file
language: python
python:
    - "2.6"
    - "2.7"

addons:
    apt:
        packages:
        - root-system
        - libroot-*-dev
        - libroot-bindings-python5.34

before_script:
    - .travis/install_cmsgemos.sh
    # Copy Travis chamber info
    - cp .travis/chamberInfo.py mapping/chamberInfo.py
    - source .travis/setupenv.sh

script:
    - ana_scans.py --scandate=current --anaType=scurve
