# Travis CI config file
language: python
python:
    - "2.6"
    - "2.7"

cache: ../root

before_install:
    - .travis/install_root.sh
    - source ../root/bin/thisroot.sh

before_script:
    - .travis/install_cmsgemos.sh
    # Copy Travis chamber info
    - cp .travis/chamberInfo.py mapping/chamberInfo.py
    - source .travis/setupenv.sh

script:
    - test_scurve.py
