# Travis CI config file
sudo: required

language: cpp

env:
    matrix:
        - OS_TYPE=centos OS_VERSION=6 DOCKER_IMAGE=gitlab-registry.cern.ch/sturdy/gemdaq_ci_worker:slc6
#       - OS_TYPE=centos OS_VERSION=7 DOCKER_IMAGE=gitlab-registry.cern.ch/sturdy/gemdaq_ci_worker:cc7

services:
    - docker


before_install:
    - sudo apt-get update
    - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
    - sudo service docker restart
    - sleep 1
    - docker pull $DOCKER_IMAGE
    - docker ps -al

script:
    - .travis/travis.sh ${OS_VERSION}
