# Travis CI config file
language: python
python:
    - "2.6"
    - "2.7"

addons:
    apt:
        packages:
        - root-system
        - libroot-*-dev
        - libroot-bindings-python5.34

script: true
